### ISSUE TITLE
Proof reading

### ISSUE THREAD

**Issue by Terry-Thompson** [learn-co-curriculum/welcome-introduction#2]
1.  I noticed in the "Introduction" section the sentence: "we'd like about Flatiron School's philosophy and the structure of this course", and I am assuming they would like it to read:  "we'd like _to talk_ about Flatiron School's philosophy and the structure of this course".  
2.   The "Accessing Course Content" section says: "You can access the courses available to you by clicking Course in the navigation on the left", and I am assuming they meant:  "You can access the courses available to you by clicking _Courses_ in the navigation on the left"

**Comment by ihollander** [comment]
Thanks for flagging these corrections @Terry-Thompson! We'll get them fixed shortly.

**Comment by ihollander** [comment]
The first correction was fixed here: https://github.com/learn-co-curriculum/welcome-introduction/commit/0cf990c1d9884e540cab011ecf8d0f32cd9d1993

The second correction will be fixed in this PR: https://github.com/learn-co-curriculum/welcome-introduction/pull/3
